### ISSUE TITLE
Rework simulation settings

### ISSUE THREAD

**Issue by luyckxn** [Calvagone/campsis#110]
In some cases, specific settings are needed to run a simulation.

The idea behind this ticket is to englobe all these settings into a settings object, that can be passed as 1 argument to the simulate method.
This settings object (constructor Settings) can accept subgroups of settings:
- Hardware settings (-> see Hardware() ): options to run simulations in parallel
- Solver settings (-> see Solver() ): options to pass to the ODE solver (e.g. atol, rtol, etc.)
- NOCB settings (-> see NOCB() ): useful settings for switching to NOCB / LOCF mode for given variables

And more settings to come...

**Comment by mattfidler** [comment]
Hi @luyckxn 

rxode2 is currently being submitted to CRAN, it should be accepted whenever CRAN wants to push it through.

I have a fix for `nlmixr2est` after that but right now CRAN binaries do not work 😦

**Comment by luyckxn** [comment]
Hi Matt,

Thanks for your message. I'm currently installing rxode2 from your GitHub repo for the CI test with GitHub actions and that works fine.
Good luck with the submission process!

**Comment by mattfidler** [comment]
Thanks
