### ISSUE TITLE
additional columns to label and comment parameters

### ISSUE THREAD

**Issue by AndreasCalvagone** [Calvagone/campsis#119]
Would be great if we could have addional fields inthe parameter object to better track and document a model.
I suggest the following:

label: text providing a human readable long name of a parameter as it would be used in reports and publications
units
comment: text field useful to enter for example the source of a certain parameter value

units: well, the units (just as plain character string, no specific requirement how it is written).

Ideally, when translating the model automatically these fields are filled automatically based on our NONMEM naming conventions, in the comment field the runname would be written.

I think this feature would help tremendously in documenting a simulation for a report. 
We could then just add the output of print(model) to the appendix and use calvaTables to make well-formated parameter tables.

**Comment by luyckxn** [comment]
Nothing to do. Ticket implemented in https://github.com/Calvagone/campsismod/issues/65 (campsismod).
