### ISSUE TITLE
when trying to run example Error in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"), 

### ISSUE THREAD

**Issue by jmccune14** [Calvagone/campsis#120]
I am trying your package.  I installed it and am running your example here:  https://calvagone.github.io/campsis.doc/.   After running this line of code: results <- model [%>%](https://rdrr.io/pkg/campsismod/man/grapes-greater-than-grapes.html) [simulate](https://calvagone.github.io/campsis.doc/reference/simulate.html)(dataset=ds, dest="rxode2", seed=1),  I get this error:  
![image](https://github.com/Calvagone/campsis/assets/60143855/5e35244c-ece5-42dd-87b6-29cfa75167a1)

**Comment by mattfidler** [comment]
You need to have Rtools installed.  The `make` is the tell-tale sign that this isn't installed.

**Comment by mattfidler** [comment]
If you are on windows, install the version of Rtools that matches your version of R:

https://cran.r-project.org/bin/windows/Rtools/

**Comment by luyckxn** [comment]
Thanks @mattfidler !
