### ISSUE TITLE
Automatic coercion from double to character was deprecated in purrr 1.0.0.

### ISSUE THREAD

**Issue by Amaranthfan** [Calvagone/campsis#121]
Automatic coercion from double to character was deprecated in purrr 1.0.0.
ℹ Please use an explicit call to `as.character()` within `map_chr()` instead.
ℹ The deprecated feature was likely used in the campsis package.

**Comment by luyckxn** [comment]
Solved in https://github.com/Calvagone/campsis/issues/118.
