### ISSUE TITLE
Function to sample from a Binomial Distribution

### ISSUE THREAD

**Issue by AndreasCalvagone** [Calvagone/campsis#124]
Could we add a short-cut function to use the rbinom function when sampling a covariate?

And along these lines, how about a generic wrapper function for distributions, that, that takes as input the function name and a list of it arguments?

**Comment by mattfidler** [comment]
In rxode2 you can use rxbinom or ribinom

**Comment by mattfidler** [comment]
I think you can use Rcpp for mrgsolve though I am less familiar with that approach

**Comment by luyckxn** [comment]
Good idea.
@AndreasCalvagone: There is already a wrapper that you can use, it is called 'FunctionDistribution' (see here:   https://calvagone.github.io/campsis.doc/reference/FunctionDistribution.html)
