### ISSUE TITLE
new error with previously working code using mrgsolve and rxode2.

### ISSUE THREAD

**Issue by jsmccune14** [Calvagone/campsis#156]
A new error is occurring with code that has worked for over 14 months on Campsis.  The error occurs when using mrgsolve.  As part of troubleshooting, I also tried it with rxode2.  I get the same error.  The error is as follows:  , 

using C++ compiler: 'G__~1.EXE (GCC) 13.2.0'

27:25: error: 'CP' was not declared in this scope
   27 | dxdt_A_CENTRAL=KSYN*(1+(CP/(CP+EC50))) - KOUT*A_CENTRAL+K21*A_PERIPHERAL-K12*A_CENTRAL;
      |                         ^~
make: *** [C:/PROGRA~1/R/R-44~1.1/etc/x64/Makeconf:296: mod_81b0a75d9f20211ec2abd0e3cf84f24c301e0ddc-mread-source.o] Error 1Error in (function (.x, .y, .f, ..., .progress = FALSE)  :

**Comment by luyckxn** [comment]
@jsmccune14 : it seems CP is not properly declared. Could you maybe send me the Campsis model so that I can help you (or post a minimalist example of the problem that I could reproduce) ? Thanks

**Comment by jsmccune14** [comment]
Thank you for your response. The R script ran for over 12 months before this error started. But here's the model.  

model<-model_suite$nonmem$"advan3_trans4" 
model <- model %>% replace(Equation("CL", "THETA_CL*exp(ETA_CL)*pow(BW/70, 0.75)"))
model<- model %>% replace(Equation("V1", "THETA_V1*exp(ETA_V1)*pow(BW/70,1)"))

model <- model %>% add(Equation("EC50","3.65")) 
model <- model %>% add(Equation("BL","0.228")) 
model <- model %>% add(Equation("KOUT","CL/V1")) 
model <- model %>% add(Equation("KSYN","BL*KOUT"))
model <- model %>% add(Equation("K12","Q/V1"))
model <- model %>% add(Equation("K21","Q/V2"))

model <- model %>% add(InitialCondition(compartment=1, rhs="BL"))
# Differential equations
model <-model %>% replace(Ode("A_CENTRAL", "KSYN*(1+(CP/(CP+EC50))) - KOUT*A_CENTRAL+K21*A_PERIPHERAL-K12*A_CENTRAL"))
model <- model %>% replace(Ode("A_PERIPHERAL", "K12*A_CENTRAL - K21*A_PERIPHERAL"))

**Comment by luyckxn** [comment]
Hi [jsmccune14](https://github.com/jsmccune14),

Previously, concentration variable was 'CP' in all the NONMEM models (model_suite$nonmem$...). This was changed some time ago and the concentration variable is always 'CONC'. That's probably the reason your model does not compile anymore. At any time, you can print your model in the console using the print statement and check it is correct. (e.g. print(model))

The following code works as expected:
```
library(campsis)

model <- model_suite$nonmem$"advan3_trans4" %>%
  replace(Equation("CL", "THETA_CL*exp(ETA_CL)*pow(BW/70, 0.75)")) %>%
  replace(Equation("V1", "THETA_V1*exp(ETA_V1)*pow(BW/70, 1)"))

model <- model %>%
  add(Equation("EC50","3.65")) %>%
  add(Equation("BL","0.228")) %>%
  add(Equation("KOUT","CL/V1")) %>% 
  add(Equation("KSYN","BL*KOUT")) %>% 
  add(Equation("K12","Q/V1")) %>%
  add(Equation("K21","Q/V2"))

model <- model %>%
  add(InitialCondition(compartment=1, rhs="BL"))

model <- model %>%
  delete(Equation("CONC")) %>% # Delete CONC in ERROR block
  delete(Equation("F")) %>% # Delete F in ODE block
  add(Equation("CONC", "A_CENTRAL/S1"), pos=Position(OdeRecord(), after=FALSE)) %>% # Add CONC before first ODE
  replace(Ode("A_CENTRAL", "KSYN*(1+(CONC/(CONC+EC50))) - KOUT*A_CENTRAL+K21*A_PERIPHERAL-K12*A_CENTRAL")) %>%
  replace(Ode("A_PERIPHERAL", "K12*A_CENTRAL - K21*A_PERIPHERAL"))

dataset <- Dataset(1) %>%
  add(Observations(0:100)) %>%
  add(Covariate("BW", 70))
                   
results1 <- simulate(model=model, dataset=dataset, outvars="CONC", dest="rxode2", seed=1)
spaghettiPlot(results1, "CONC")

results2 <- simulate(model=model, dataset=dataset, outvars="CONC", dest="mrgsolve", seed=1)
spaghettiPlot(results2, "CONC")
```

**Comment by luyckxn** [comment]
I hope I solve your problem.

**Comment by jsmccune14** [comment]
I was able to run the code with your edits.  Thank you for the update.

**Comment by luyckxn** [comment]
You're welcome!
