### ISSUE TITLE
Where is the list of model_suites?

### ISSUE THREAD

**Issue by jsmccune14** [Calvagone/campsis#159]
I was hoping for the list of model_suites in campsis.  I didn't see it online or in the R documentation.  Thank you!

**Comment by luyckxn** [comment]
Hi [jsmccune14](https://github.com/jsmccune14),

The model library can be found in the campsismod package (variable 'model_suite'), which is automatically loaded when the campsis package is loaded.

Here is an example of how you can use the models from the library:

```
# Load 1-compartment PK model, first order absorption with lag time
model <- model_suite$pk$'1cpt_fo_lag'

# Load NONMEM model template for ADVAN1 TRANS1
model <- model_suite$nonmem$advan1_trans1

# Load 1-compartment PK full TMDD model
model <- model_suite$tmdd$'1cpt_fo_tmdd_full'

# Print the model code
print(model)
```

I hope it helps.
