### ISSUE TITLE
error unknown statement

### ISSUE THREAD

**Issue by AndreasCalvagone** [Calvagone/campsis#65]
When there are spaces after the section heading in the model code e.g. [ERROR], or [INIT],
campsis gives an error saying 'unknown statement'.

**Comment by luyckxn** [comment]
Thanks for posting this issue. I will have a look.
As it is an issue in campsismod, I will simply close this issue and duplicate it into campsismod.
See https://github.com/Calvagone/campsismod/issues/38.
